### Read data
GET http://localhost:5000/data/import/csv/C:/Users/TheAncientOwl/Code/data-analysis-tool/server/common/test-data/pca-data.agriculture.csv

### Read data
GET http://localhost:5000/data/import/csv/C:/Users/TheAncientOwl/Code/data-analysis-tool/server/test-data/pca-data-na.csv

### Read data
GET http://localhost:5000/data/import/csv/C:/Users/TheAncientOwl/Code/data-analysis-tool/server/test-data/factor-analysis-bfi.csv

### Print server's dataframe head
GET http://localhost:5000/printhead 

###
POST http://localhost:5000/data/drop/rows+cols
Content-Type: application/json

{
  "labels": ["EA", "EAM", "EAF"],
  "mangoIDs": [4, 7, 2]
}

### get rows
GET http://localhost:5000/data/rows-between/0/20

###
POST http://localhost:5000/data/scale
Content-Type: application/json

{
  "method": "maximum_absolute_scaling"
}

###
POST http://localhost:5000/data/scale
Content-Type: application/json

{
  "method": "min_max_scaling"
}

###
POST http://localhost:5000/data/scale
Content-Type: application/json

{
  "method": "z_score_scaling"
}

###
POST http://localhost:5000/data/scale
Content-Type: application/json

{
  "method": "robust_scaling"
}

###
POST http://localhost:5000/data/scale
Content-Type: application/json

{
  "method": "wdawdw"
}


### Delete dataframe
POST http://localhost:5000/data/drop-all


### Save data
POST http://localhost:5000/data/export/csv/name/DateExported.csv/path/C:/Users/TheAncientOwl/Code/ddata-analysis-tool/server

### get page
GET http://localhost:5000/data/page/1/page-size/3

###
GET http://localhost:5000/data/rows-count

###
POST http://localhost:5000/data/export/dataframe/csv
Content-Type: application/json

{
  "savePath": "C:\\Users\\TheAncientOwl\\Desktop\\Test.csv",
  "index": ["idx1", "idx2"],
  "columns": ["col1", "col2"],
  "data": [[1, 2], [3, 4]]
}
