### Read data
GET http://localhost:5000/data/import/csv/C:/Users/TheAncientOwl/Code/data-analysis-tool/server/Date.csv

### Print server's dataframe head
GET http://localhost:5000/printhead 

### Save data
POST http://localhost:5000/data/export/csv/name/DateExported.csv/path/C:/Users/TheAncientOwl/Code/ddata-analysis-tool/server





### Delete dataframe
POST http://localhost:5000/data/drop-all



### get rows
GET http://localhost:5000/data/rows-between/0/20

### get page
GET http://localhost:5000/data/page/1/page-size/3

###
GET http://localhost:5000/data/rows-count