### Save data
GET http://localhost:5000/data/export/csv/name/DateExported.csv/path/C:/Users/TheAncientOwl/Code/data-analysis-tool/backend

### Print server's dataframe head
GET http://localhost:5000/printhead 

### Delete dataframe
GET http://localhost:5000/data/delete

### Read data
GET http://localhost:5000/data/import/csv/C:/Users/TheAncientOwl/Code/data-analysis-tool/server/Date.csv

###
GET http://localhost:5000/data/summary

###
POST http://localhost:5000/data/plots/plot
Content-Type: application/json

{
  "x": "EA",
  "y": "EAM",
  "xLab": "EA_lab",
  "yLab": "EAM_lab",
  "title": "Test plot"
}

### Read data
GET http://localhost:5000/data/import/csv/C:/Users/TheAncientOwl/Code/data-analysis-tool/server/Date.csv

### get rows
GET http://localhost:5000/data/rows-between/0/20

### get page
GET http://localhost:5000/data/page/1/page-size/3

###
GET http://localhost:5000/data/rows-count